### ISSUE TITLE
Restarts for V1_4 forcing

### ISSUE THREAD

**Issue by MatthisAuger** [OceansAus/025deg_jra55_ryf#11]
Hi,

I have been trying to run this model from a restart located in `/g/data/ik11/outputs/access-om2-025/025deg_jra55_ryf9091_gadi/restart300`, which gives me this error: 

> FATAL from PE    46: fms_io(restore_state_all): Checksum of input field U 5FC2712DA9FBC894 does not match value D34C86DBF9ED8CD5 stored in OCEAN_VELOCITY.RES.NC

The model runs well when there is no restart prescribed. I'm thinking the error could be due to the difference in forcing files, with those restarts using as atmosphere input `/g/data/ua8/JRA55-do/RYF/v1-3/`, while the configuration on this project uses `/g/data/ik11/inputs/JRA-55/RYF/v1-4/`

Is there any restart available for this configuration or should I rerun the model from scratch?

Thank you

**Comment by aekiss** [comment]
If you want to start from a particular restart you should use the same configuration, which seems from `/g/data/ik11/outputs/access-om2-025/025deg_jra55_ryf9091_gadi/metadata.yaml` to be https://github.com/rmholmes/025deg_jra55_ryf/tree/ryf9091_gadi

More details here: https://github.com/COSIMA/access-om2/wiki/Tutorials#starting-a-new-experiment-using-restarts-from-a-previous-experiment

**Comment by MatthisAuger** [comment]
My question was more about if there was any restart for the configuration of the main branch here, because I have not been able to find some. 

But I guess it's simpler if I just use previous configurations with the restarts that I found. Thanks!

**Comment by aekiss** [comment]
The latest configuration in this repo includes updated topography, so there are no restarts available for it.
